spring:
    applicationContext: ['conf/applicationContext.xml', 'conf/basicAuthSecurityContext.xml']

    beanProfiles: ['production', 'feature1', 'feature2']

    useSpringSecurity: true

exampleProperty: This was your example property

logging:
    level: INFO
    console:
        enabled: true
        threshold: DEBUG
        
http:
    port: 8080
    adminUsername: admin
    adminPassword: admin
    rootPath: /service/*